-- =========================================================
-- 1️⃣ Create USER_ROLES table
-- =========================================================
CREATE TABLE IF NOT EXISTS user_roles (
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT CHECK (role IN ('admin', 'student')),
  PRIMARY KEY (user_id)
);

-- =========================================================
-- 2️⃣ Create BOOKS table
-- =========================================================
CREATE TABLE IF NOT EXISTS books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  isbn TEXT UNIQUE NOT NULL,
  genre TEXT,
  total_copies INT DEFAULT 0,
  available_copies INT DEFAULT 0
);

-- =========================================================
-- 3️⃣ Create CHECKOUTS table
-- =========================================================
CREATE TABLE IF NOT EXISTS checkouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  book_id BIGINT REFERENCES books(id) ON DELETE CASCADE,
  status TEXT CHECK (status IN ('checked_out', 'returned')) DEFAULT 'checked_out',
  issued_at TIMESTAMPTZ DEFAULT NOW(),
  returned_at TIMESTAMPTZ
);

-- =========================================================
-- 4️⃣ Create a helper function to check for admin role
-- =========================================================
CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM user_roles
    WHERE user_roles.user_id = auth.uid() AND user_roles.role = 'admin'
  );
END;
$$;

-- =========================================================
-- 5️⃣ Enable Row Level Security (RLS)
-- =========================================================
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE books ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkouts ENABLE ROW LEVEL SECURITY;

-- =========================================================
-- 6️⃣ Define RLS Policies
-- =========================================================

-- ========== USER_ROLES ==========

-- First, drop all existing policies on user_roles to ensure a clean slate.
DROP POLICY IF EXISTS "Admins can manage roles" ON user_roles;
DROP POLICY IF EXISTS "Admins can insert user roles" ON user_roles;
DROP POLICY IF EXISTS "Admins can update user roles" ON user_roles;
DROP POLICY IF EXISTS "Admins can delete user roles" ON user_roles;
DROP POLICY IF EXISTS "Users can view their own role" ON user_roles;
DROP POLICY IF EXISTS "Admins can view all roles" ON user_roles;


-- Admins can do anything on the user_roles table
CREATE POLICY "Admins can manage roles"
ON user_roles
FOR ALL
USING (is_admin())
WITH CHECK (is_admin());


-- ========== BOOKS ==========
-- First, drop all existing policies on books to ensure a clean slate.
DROP POLICY IF EXISTS "Allow read access for all" ON books;
DROP POLICY IF EXISTS "Admins can manage books" ON books;

-- Everyone can read books
CREATE POLICY "Allow read access for all"
ON books
FOR SELECT
USING (true);

-- Only admins can add, update, or delete books
CREATE POLICY "Admins can manage books"
ON books
FOR ALL
USING (is_admin())
WITH CHECK (is_admin());


-- ========== CHECKOUTS ==========
-- First, drop all existing policies on checkouts to ensure a clean slate.
DROP POLICY IF EXISTS "Admins can manage all checkouts" ON checkouts;
DROP POLICY IF EXISTS "Students can view their own checkouts" ON checkouts;
DROP POLICY IF EXISTS "Students can create their own checkouts" ON checkouts;


-- Admins can view or manage all checkouts
CREATE POLICY "Admins can manage all checkouts"
ON checkouts
FOR ALL
USING (is_admin())
WITH CHECK (is_admin());

-- Students can view their own checkouts
CREATE POLICY "Students can view their own checkouts"
ON checkouts
FOR SELECT
USING (user_id = auth.uid());

-- Students can create their own checkouts
CREATE POLICY "Students can create their own checkouts"
ON checkouts
FOR INSERT
WITH CHECK (user_id = auth.uid());
